In [21]:
!pip install line-profiler
!python3 -m pip install --upgrade pip


[notice] A new release of pip is available: 23.3.2 -> 25.0.1
[notice] To update, run: C:\Users\vinit\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ------------ --------------------------- 0.6/1.8 MB 11.5 MB/s eta 0:00:01
   --------------- ------------------------ 0.7/1.8 MB 7.6 MB/s eta 0:00:01
   ------------------- -------------------- 0.9/1.8 MB 6.4 MB/s eta 0:00:01
   -------------------- ------------------- 0.9/1.8 MB 6.6 MB/s eta 0:00:01
   -------------------- ------------------- 0.9/1.8 MB 6.6 MB/s eta 0:00:01
   ---------------------- ----------------- 1.0/1.8 MB 3.9 MB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 5.2 MB/s eta 0:00:01
   -------------------------------------- - 1.8/1.8 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 4.7 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 23.3.2
    Uninstalling pip-23.3.2:
      Successfully uninstalled pip-23.3.2


In [24]:
!pip install memory-profiler


In [37]:
import timeit

In [38]:
def matrix_addition(A,B):
    C = []
    for i in range(len(A)):
        C.append([])
        for j in range(len(A[i])):
            C[i].append(A[i][j] + B[i][j])

    return C

a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[9,8,7],[6,5,4],[3,2,1]]

print(matrix_addition(a,b))


[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [39]:
def matrix_multiplication_count(A, B):
    C = []
    num_mult = 0
    num_add = 0

    for i in range(len(A)):  # m
        C.append([])
        for j in range(len(B[0])):  # p
            C[i].append(0)
            for k in range(len(B)):  # n
                C[i][j] += A[i][k] * B[k][j]
                num_mult += 1  # Counting multiplications
                num_add += 1  # Counting additions
    
    return C, num_mult, num_add

# Sample matrices
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12], [13,14,15,16]]
b = [[17,18,19,20],[21,22,23,24],[25,26,27,28], [29,30,31,32]]

C, mults, adds = matrix_multiplication_count(a, b)

print(f"Mul Operation = {mults}\nAdd Operation = {adds}\nTotal Operation = {mults + adds}")
print(f'MUL = {C}')


Mul Operation = 64
Add Operation = 64
Total Operation = 128
MUL = [[250, 260, 270, 280], [618, 644, 670, 696], [986, 1028, 1070, 1112], [1354, 1412, 1470, 1528]]


In [40]:
execution_time = timeit.timeit(lambda: matrix_multiplication_count(a,b), number=100) / 100
print(f"Avg Execution Time: {execution_time:.12f} seconds")

Avg Execution Time: 0.000033192000 seconds


In [41]:
import psutil
import time

# Get initial CPU and RAM usage
cpu_before = psutil.cpu_percent(interval=0.1)
ram_before = psutil.virtual_memory().used

start_time = time.time()
C = matrix_multiplication_count(a, b)
print (C)
end_time = time.time()

# Get final CPU and RAM usage
cpu_after = psutil.cpu_percent(interval=0.1)
ram_after = psutil.virtual_memory().used

execution_time = end_time - start_time
ram_used = (ram_after - ram_before) / (1024 * 1024)  # Convert to MB

print(f"Execution Time: {execution_time:.12f} seconds")
print(f"CPU Usage Before: {cpu_before}% | After: {cpu_after}%")
print(f"Memory Used: {ram_used:.12f} MB")

([[250, 260, 270, 280], [618, 644, 670, 696], [986, 1028, 1070, 1112], [1354, 1412, 1470, 1528]], 64, 64)
Execution Time: 0.001251697540 seconds
CPU Usage Before: 32.9% | After: 72.4%
Memory Used: -0.238281250000 MB


In [42]:
import cProfile

cProfile.run('matrix_multiplication_count(a, b)')

         45 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 787158366.py:1(matrix_multiplication_count)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
       21    0.000    0.000    0.000    0.000 {built-in method builtins.len}
       20    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




In [43]:
from line_profiler import LineProfiler

lp = LineProfiler()
lp.add_function(matrix_multiplication_count)
lp.enable()
C = matrix_multiplication_count(a, b)
lp.disable()
lp.print_stats()

Timer unit: 1e-07 s

Total time: 0.0003269 s
File: C:\Users\vinit\AppData\Local\Temp\ipykernel_31580\787158366.py
Function: matrix_multiplication_count at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def matrix_multiplication_count(A, B):
     2         1         12.0     12.0      0.4      C = []
     3         1          7.0      7.0      0.2      num_mult = 0
     4         1          4.0      4.0      0.1      num_add = 0
     5                                           
     6         5         81.0     16.2      2.5      for i in range(len(A)):  # m
     7         4         53.0     13.2      1.6          C.append([])
     8        20        194.0      9.7      5.9          for j in range(len(B[0])):  # p
     9        16        166.0     10.4      5.1              C[i].append(0)
    10        80        707.0      8.8     21.6              for k in range(len(B)):  # n
    11        64       1064.0     16.6

In [44]:
from memory_profiler import profile

@profile
def matrix_multiplication_count(A, B):
    C = []
    num_mult = 0
    num_add = 0

    for i in range(len(A)):  # m
        C.append([])
        for j in range(len(B[0])):  # p
            C[i].append(0)
            for k in range(len(B)):  # n
                C[i][j] += A[i][k] * B[k][j]
                num_mult += 1  # Counting multiplications
                num_add += 1  # Counting additions
    
    return C, num_mult, num_add

# Sample matrices
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12], [13,14,15,16]]
b = [[17,18,19,20],[21,22,23,24],[25,26,27,28], [29,30,31,32]]

C, mults, adds = matrix_multiplication_count(a, b)

print(f"Mul Operation = {mults}\nAdd Operation = {adds}\nTotal Operation = {mults + adds}")
print(f'MUL = {C}')


%load_ext memory_profiler
%mprun -f matrix_multiplication_count matrix_multiplication_count(a, b)


ERROR: Could not find file C:\Users\vinit\AppData\Local\Temp\ipykernel_31580\3644038228.py
Mul Operation = 64
Add Operation = 64
Total Operation = 128
MUL = [[250, 260, 270, 280], [618, 644, 670, 696], [986, 1028, 1070, 1112], [1354, 1412, 1470, 1528]]
The memory_profiler extension is already loaded. To reload it, use:
  %reload_ext memory_profiler
ERROR: Could not find file C:\Users\vinit\AppData\Local\Temp\ipykernel_31580\3644038228.py



Filename: C:\Users\vinit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\memory_profiler.py

Line #    Mem usage    Increment  Occurrences   Line Contents
  1185    103.9 MiB    103.9 MiB           1               @wraps(wrapped=func)
  1186                                                     def wrapper(*args, **kwargs):
  1187    103.9 MiB      0.0 MiB           1                   prof = get_prof()
  1188    103.9 MiB      0.0 MiB           1                   val = prof(func)(*args, **kwargs)
  1189    103.9 MiB      0.0 MiB           1                   show_results_bound(prof)
  1190    103.9 MiB      0.0 MiB           1                   return val

In [45]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12], [13,14,15,16]])
b = np.array([[17,18,19,20],[21,22,23,24],[25,26,27,28], [29,30,31,32]])

start_time = time.time()
c = np.dot(a, b)
end_time = time.time()

execution_time = end_time - start_time
print(f"Execution Time: {execution_time:.12f} seconds")
print(f'MUL = {c}')


Execution Time: 0.000000000000 seconds
MUL = [[ 250  260  270  280]
 [ 618  644  670  696]
 [ 986 1028 1070 1112]
 [1354 1412 1470 1528]]


In [1]:
import dis

def matrix_multiplication_count(A, B):
    C = []
    num_mult = 0
    num_add = 0

    for i in range(len(A)):  # m
        C.append([])
        for j in range(len(B[0])):  # p
            C[i].append(0)
            for k in range(len(B)):  # n
                C[i][j] += A[i][k] * B[k][j]
                num_mult += 1  # Counting multiplications
                num_add += 1  # Counting additions
    
    return C, num_mult, num_add

# Sample matrices
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12], [13,14,15,16]]
b = [[17,18,19,20],[21,22,23,24],[25,26,27,28], [29,30,31,32]]

C, mults, adds = matrix_multiplication_count(a, b)

print(f"Mul Operation = {mults}\nAdd Operation = {adds}\nTotal Operation = {mults + adds}")
print(f'MUL = {C}\n-------------------------------')

print(dis.dis(matrix_multiplication_count))

Mul Operation = 64
Add Operation = 64
Total Operation = 128
MUL = [[250, 260, 270, 280], [618, 644, 670, 696], [986, 1028, 1070, 1112], [1354, 1412, 1470, 1528]]
-------------------------------
  4           0 BUILD_LIST               0
              2 STORE_FAST               2 (C)

  5           4 LOAD_CONST               1 (0)
              6 STORE_FAST               3 (num_mult)

  6           8 LOAD_CONST               1 (0)
             10 STORE_FAST               4 (num_add)

  8          12 LOAD_GLOBAL              0 (range)
             14 LOAD_GLOBAL              1 (len)
             16 LOAD_FAST                0 (A)
             18 CALL_FUNCTION            1
             20 CALL_FUNCTION            1
             22 GET_ITER
        >>   24 FOR_ITER                62 (to 150)
             26 STORE_FAST               5 (i)

  9          28 LOAD_FAST                2 (C)
             30 LOAD_METHOD              2 (append)
             32 BUILD_LIST               0
            